version: '3'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  app:
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
