version: '3'
services:
  db:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: railsbase_development
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    restart: always
    command: mysqld --character-set-server=utf8mb4
    volumes:
      - ./docker/mysql/db/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: docker
      DATABASE_PASSWORD: docker
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 3m
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=docker
      - PMA_PASSWORD=docker
    restart: always
    ports:
      - 8080:80
